import type { ClassItem } from "@/src/components/cari-kelas/ClassCard";

export const KELAS: ClassItem[] = [
  {
    category: "COMPUTER SCIENCE",
    campus: "Binus University",
    badge: "Bootcamp",
    title: "Booster Bootcamp",
    desc: "Seluruh materi jurusan computer science dari semester 1 - 4",
    date: "10 Januari 2026",
    mode: "Online",
    duration: "Selamanya",
    tags: ["ComputerScience", "SainTek"],
    rating: "4.9",
    reviews: "340",
  },
  {
    category: "COMPUTER SCIENCE",
    campus: "Binus University",
    badge: "Bootcamp",
    title: "Adeni Bootcamp",
    desc: "Materi Jurusan Computer Science semester 3",
    date: "10 Januari 2026",
    mode: "Online",
    duration: "Tanpa Batas",
    tags: ["ComputerScience", "SainTek"],
    rating: "4.9",
    reviews: "340",
  },
  {
    category: "COMPUTER SCIENCE",
    campus: "Binus University",
    badge: "Bootcamp",
    title: "Ini Bootcamp",
    desc: "Seluruh materi jurusan computer science dari semester 1 - 4",
    date: "10 Januari 2026",
    mode: "Online",
    duration: "Tanpa Batas",
    tags: ["ComputerScience", "SainTek"],
    rating: "4.9",
    reviews: "340",
  },
  {
    category: "COMPUTER SCIENCE",
    campus: "Binus University",
    badge: "Bootcamp",
    title: "Boat Bootcamp",
    desc: "Seluruh materi jurusan computer science dari semester 1 - 4",
    date: "10 Januari 2026",
    mode: "Online",
    duration: "Tanpa Batas",
    tags: ["ComputerScience", "SainTek"],
    rating: "4.9",
    reviews: "340",
  },
  {
    category: "COMPUTER SCIENCE",
    campus: "Binus University",
    badge: "Bootcamp",
    title: "Rooster Bootcamp",
    desc: "Seluruh materi jurusan computer science dari semester 1 - 4",
    date: "10 Januari 2026",
    mode: "Online",
    duration: "Tanpa Batas",
    tags: ["ComputerScience", "SainTek"],
    rating: "4.9",
    reviews: "340",
  },
  {
    category: "COMPUTER SCIENCE",
    campus: "Binus University",
    badge: "Bootcamp",
    title: "Rocket Bootcamp",
    desc: "Seluruh materi jurusan computer science dari semester 1 - 4",
    date: "10 Januari 2026",
    mode: "Online",
    duration: "Tanpa Batas",
    tags: ["ComputerScience", "SainTek"],
    rating: "4.9",
    reviews: "340",
  },
];
